name: copy_central
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.17.0 <3.5.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml_edit: ^2.2.1
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
